version: 1
formatters:
  simple:
    format: '%(name)s, %(funcName)s, %(levelname)s, %(message)s'
  csv:
    format: '%(asctime)s.%(msecs)03d,%(module)s,%(funcName)s,%(levelname)s,"%(message)s"'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: rich.logging.RichHandler
    level: 0
    formatter: simple
    rich_tracebacks: True
loggers:
  Logging_Test:
    level: DEBUG
    handlers: [console]
    propagate: False
  core.telemetry_handler:
    level: DEBUG
    handlers: [console]
    propagate: False
  matplotlib:
    level: INFO
    handlers: [console]
    propagate: False
root:
  level: INFO
  handlers: [console]
